// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Calculator: typeof import('./src/components/Calculator.vue')['default']
    Card: typeof import('./src/components/Card.vue')['default']
    ChartCard: typeof import('./src/components/ChartCard.vue')['default']
    Circle: typeof import('./src/components/Circle.vue')['default']
    Docker: typeof import('./src/components/Docker.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    ListItem: typeof import('./src/components/ListItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VarButton: typeof import('@varlet/ui')['_ButtonComponent']
    VarCheckbox: typeof import('@varlet/ui')['_CheckboxComponent']
    VarCounter: typeof import('@varlet/ui')['_CounterComponent']
    VarDatePicker: typeof import('@varlet/ui')['_DatePickerComponent']
    VarDialog: typeof import('@varlet/ui')['_DialogComponent']
    VarForm: typeof import('@varlet/ui')['_FormComponent']
    VarIcon: typeof import('@varlet/ui')['_IconComponent']
    VarInput: typeof import('@varlet/ui')['_InputComponent']
    VarPopup: typeof import('@varlet/ui')['_PopupComponent']
    VarSpace: typeof import('@varlet/ui')['_SpaceComponent']
    VarTimePicker: typeof import('@varlet/ui')['_TimePickerComponent']
  }
  export interface ComponentCustomProperties {
    vRipple: typeof import('@varlet/ui')['_RippleComponent']
  }
}
