/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Calculator: typeof import('./src/components/Calculator.vue')['default']
    Card: typeof import('./src/components/Card.vue')['default']
    ChartCard: typeof import('./src/components/ChartCard.vue')['default']
    Circle: typeof import('./src/components/Circle.vue')['default']
    Dock: typeof import('./src/components/Dock.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    ListItem: typeof import('./src/components/ListItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VarButton: typeof import('@varlet/ui')['_ButtonComponent']
    VarCheckbox: typeof import('@varlet/ui')['_CheckboxComponent']
    VarCollapse: typeof import('@varlet/ui')['_CollapseComponent']
    VarCollapseItem: typeof import('@varlet/ui')['_CollapseItemComponent']
    VarDatePicker: typeof import('@varlet/ui')['_DatePickerComponent']
    VarDialog: typeof import('@varlet/ui')['_DialogComponent']
    VarForm: typeof import('@varlet/ui')['_FormComponent']
    VarIcon: typeof import('@varlet/ui')['_IconComponent']
    VarInput: typeof import('@varlet/ui')['_InputComponent']
    VarPopup: typeof import('@varlet/ui')['_PopupComponent']
    VarSpace: typeof import('@varlet/ui')['_SpaceComponent']
    VarTimePicker: typeof import('@varlet/ui')['_TimePickerComponent']
  }
  export interface ComponentCustomProperties {
    vRipple: typeof import('@varlet/ui')['_RippleComponent']
  }
}
